# Generated by Django 3.2.3 on 2021-06-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productinshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_name', models.CharField(max_length=255)),
                ('client_mobile', models.IntegerField()),
                ('Products_name', models.CharField(max_length=255)),
                ('Quantity', models.FloatField()),
                ('price1', models.FloatField()),
                ('randid', models.IntegerField()),
                ('Userdid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Product_id',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
