# Generated by Django 3.2.3 on 2021-06-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210607_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetailLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Client_name', models.CharField(max_length=255)),
                ('client_mobile', models.IntegerField()),
                ('randid', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_id',
            field=models.CharField(max_length=255),
        ),
    ]
