# Generated by Django 3.2.3 on 2021-06-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_billdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userid', models.IntegerField()),
                ('Client_name', models.CharField(max_length=255)),
                ('client_mobile', models.IntegerField()),
                ('randId', models.IntegerField()),
                ('BillDate', models.DateTimeField(auto_now_add=True)),
                ('TotalAmt', models.FloatField()),
                ('BillCheck', models.CharField(max_length=100)),
            ],
        ),
    ]
