# Generated by Django 3.2.3 on 2021-06-16 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_clientbilldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetails',
            name='BillDate1',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
