# Generated by Django 3.2.3 on 2021-06-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_billdetails_billdate1'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userid', models.IntegerField()),
                ('Client_name', models.CharField(max_length=255)),
                ('client_mobile', models.IntegerField()),
                ('randId', models.IntegerField()),
                ('BillConfirmDate', models.DateTimeField(auto_now_add=True)),
                ('paymentDate', models.DateTimeField(auto_now=True)),
                ('TotalAmt', models.FloatField()),
                ('DonePayment', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ClientBillDetails',
        ),
        migrations.RemoveField(
            model_name='billdetails',
            name='BillDate1',
        ),
        migrations.AddField(
            model_name='billdetails',
            name='BillConfirmDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
