# Generated by Django 3.2.3 on 2021-07-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210619_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userid', models.IntegerField()),
                ('Client_name', models.CharField(max_length=255)),
                ('client_mobile', models.IntegerField()),
                ('Client_Add1', models.CharField(max_length=255)),
                ('Client_add2', models.CharField(max_length=255)),
                ('Client_add3', models.CharField(max_length=255)),
                ('Client_pin', models.IntegerField()),
                ('randId', models.IntegerField()),
            ],
        ),
    ]
